version: "3.4"
services:
  lockrelay:
    container_name: lockrelay
    restart: unless-stopped
    image: ${IMAGE}
    networks:
      default:
      z_internal:
    environment:
      - SW_TOKEN=${SW_TOKEN}
      - SW_SECRET=${SW_SECRET}
      - API_TOKEN=${API_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
networks:
  z_internal:
    external: true
